/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

/**
 *
 * @author ferreira
 */
public class EscolherDificuldade extends javax.swing.JFrame {
    private int Escolha;
    /**
     * Creates new form EscolherDificuldade
     */
    public EscolherDificuldade() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jChooseIzi = new javax.swing.JButton();
        jChooseHard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(409, 503));
        setResizable(false);
        getContentPane().setLayout(null);

        jChooseIzi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/izipizi.png"))); // NOI18N
        jChooseIzi.setMaximumSize(new java.awt.Dimension(150, 29));
        jChooseIzi.setMinimumSize(new java.awt.Dimension(150, 29));
        jChooseIzi.setPreferredSize(new java.awt.Dimension(150, 29));
        jChooseIzi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChooseIziMouseClicked(evt);
            }
        });
        jChooseIzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChooseIziActionPerformed(evt);
            }
        });
        getContentPane().add(jChooseIzi);
        jChooseIzi.setBounds(110, 400, 180, 80);

        jChooseHard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/Impossible.png"))); // NOI18N
        jChooseHard.setMaximumSize(new java.awt.Dimension(150, 29));
        jChooseHard.setMinimumSize(new java.awt.Dimension(150, 29));
        jChooseHard.setPreferredSize(new java.awt.Dimension(150, 29));
        jChooseHard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChooseHardMouseClicked(evt);
            }
        });
        jChooseHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChooseHardActionPerformed(evt);
            }
        });
        getContentPane().add(jChooseHard);
        jChooseHard.setBounds(110, 300, 180, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-90, -40, 530, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChooseHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChooseHardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChooseHardActionPerformed

    private void jChooseIziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChooseIziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChooseIziActionPerformed

    private void jChooseIziMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChooseIziMouseClicked
        EscolherQuemComeca tela = new EscolherQuemComeca();
        tela.setVisible(true);
        tela.DadosDaTela(Escolha,0);
        this.dispose();
               
    }//GEN-LAST:event_jChooseIziMouseClicked

    private void jChooseHardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChooseHardMouseClicked
        EscolherQuemComeca tela = new EscolherQuemComeca();
        tela.setVisible(true);
        tela.DadosDaTela(Escolha,1);
        this.dispose();
    }//GEN-LAST:event_jChooseHardMouseClicked

    public void EscolherModo1(){
        Escolha=1;
        
    }
    public void EscolherModo2(){
        Escolha=2;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolherDificuldade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChooseHard;
    private javax.swing.JButton jChooseIzi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
