/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

/**
 *
 * @author ferreira
 */
public class EscolherModo extends javax.swing.JFrame {

    /**
     * Creates new form EscolherModo
     */
    public EscolherModo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jChooseHuman = new javax.swing.JButton();
        jChooseMachine = new javax.swing.JButton();
        jIPMachine = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(409, 503));
        setResizable(false);
        getContentPane().setLayout(null);

        jChooseHuman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/humanvs.png"))); // NOI18N
        jChooseHuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChooseHumanMouseClicked(evt);
            }
        });
        jChooseHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChooseHumanActionPerformed(evt);
            }
        });
        getContentPane().add(jChooseHuman);
        jChooseHuman.setBounds(120, 290, 180, 80);

        jChooseMachine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/machinevs.png"))); // NOI18N
        jChooseMachine.setActionCommand("");
        jChooseMachine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChooseMachineMouseClicked(evt);
            }
        });
        jChooseMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChooseMachineActionPerformed(evt);
            }
        });
        getContentPane().add(jChooseMachine);
        jChooseMachine.setBounds(120, 380, 180, 80);

        jIPMachine.setText("IP_Maquina");
        jIPMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIPMachineActionPerformed(evt);
            }
        });
        getContentPane().add(jIPMachine);
        jIPMachine.setBounds(100, 470, 235, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-90, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChooseMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChooseMachineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChooseMachineActionPerformed

    private void jChooseHumanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChooseHumanMouseClicked
        EscolherDificuldade tela = new EscolherDificuldade();
        tela.setVisible(true);
        tela.EscolherModo1();
        this.dispose();
    }//GEN-LAST:event_jChooseHumanMouseClicked

    private void jChooseMachineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChooseMachineMouseClicked
        EscolherDificuldade tela = new EscolherDificuldade();
        tela.setVisible(true);
        tela.EscolherModo2();
        this.dispose();
    }//GEN-LAST:event_jChooseMachineMouseClicked

    private void jChooseHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChooseHumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChooseHumanActionPerformed

    private void jIPMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIPMachineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIPMachineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherModo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolherModo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jChooseHuman;
    private javax.swing.JButton jChooseMachine;
    private javax.swing.JTextField jIPMachine;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
