/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ferreira
 */
public class InterfaceJogo extends javax.swing.JFrame {
    int Escolha,Dificuldade,QuemComeca;
    Jogo jogo;
    /**
     * Creates new form InterfaceJogo
     */
    public InterfaceJogo() {
        initComponents();
        setLocationRelativeTo(null);
        jogo=new Jogo();
        
            
    }
    private void setPosition(){
       if(jogo.Tabuleiro[0]==0){
        jLacuna1.setText("NULL");
       }
       else if(jogo.Tabuleiro[0]==1){
          jLacuna1.setText("1");
       }
       else{
           jLacuna1.setText("2");
       }
       if(jogo.Tabuleiro[1]==0){
         jLacuna2.setText("NULL");
       }
       else if(jogo.Tabuleiro[1]==1){
          //jLacuna2.setIcon(new ImageIcon(getClass().getResource("super.png")));
          jLacuna2.setText("1");
          
       }
       else {
           jLacuna2.setText("2");
       }
       if(jogo.Tabuleiro[2]==0){
         jLacuna3.setText("NULL");
       }
       else if(jogo.Tabuleiro[2]==1){
          jLacuna3.setText("1");
       }
       else {
           jLacuna3.setText("2");
       }
       
       if(jogo.Tabuleiro[3]==0){
         jLacuna4.setText("NULL");
       }
       else if(jogo.Tabuleiro[3]==1){
          jLacuna4.setText("1");
       }
       else {
           jLacuna4.setText("2");
       }
       if(jogo.Tabuleiro[4]==0){
         jLacuna5.setText("NULL");
       }
       else if(jogo.Tabuleiro[4]==1){
          jLacuna5.setText("1");
       }
       else {
           jLacuna5.setText("2");
       }
       if(jogo.Tabuleiro[5]==0){
         jLacuna6.setText("NULL");
       }
       else if(jogo.Tabuleiro[5]==1){
          jLacuna6.setText("1");
       }
       else {
           jLacuna6.setText("2");
       }
       if(jogo.Tabuleiro[6]==0){
         jLacuna7.setText("NULL");
       }
       else if(jogo.Tabuleiro[6]==1){
          jLacuna7.setText("1");
       }
       else {
           jLacuna7.setText("2");
       }
       if(jogo.Tabuleiro[7]==0){
         jLacuna8.setText("NULL");
       }
       else if(jogo.Tabuleiro[7]==1){
          jLacuna8.setText("1");
       }
       else {
           jLacuna8.setText("2");
       }
       if(jogo.Tabuleiro[8]==0){
         jLacuna9.setText("NULL");
       }
       else if(jogo.Tabuleiro[8]==1){
          jLacuna9.setText("1");
       }
       else {
           jLacuna9.setText("2");
       }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLacuna1 = new javax.swing.JButton();
        jLacuna2 = new javax.swing.JButton();
        jLacuna3 = new javax.swing.JButton();
        jLacuna4 = new javax.swing.JButton();
        jLacuna5 = new javax.swing.JButton();
        jLacuna6 = new javax.swing.JButton();
        jLacuna7 = new javax.swing.JButton();
        jLacuna8 = new javax.swing.JButton();
        jLacuna9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        jLacuna1.setText("jButton1");
        jLacuna1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna1.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna1.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLacuna1MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna1MouseClicked(evt);
            }
        });
        jLacuna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna1ActionPerformed(evt);
            }
        });

        jLacuna2.setText("jButton1");
        jLacuna2.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna2.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna2.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLacuna2MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna2MouseClicked(evt);
            }
        });
        jLacuna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna2ActionPerformed(evt);
            }
        });

        jLacuna3.setText("jButton1");
        jLacuna3.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna3.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna3.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna3MouseClicked(evt);
            }
        });
        jLacuna3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna3ActionPerformed(evt);
            }
        });

        jLacuna4.setText("jButton1");
        jLacuna4.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna4.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna4.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna4MouseClicked(evt);
            }
        });
        jLacuna4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna4ActionPerformed(evt);
            }
        });

        jLacuna5.setText("jButton1");
        jLacuna5.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna5.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna5.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna5MouseClicked(evt);
            }
        });
        jLacuna5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna5ActionPerformed(evt);
            }
        });

        jLacuna6.setText("jButton1");
        jLacuna6.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna6.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna6.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna6MouseClicked(evt);
            }
        });
        jLacuna6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna6ActionPerformed(evt);
            }
        });

        jLacuna7.setText("jButton1");
        jLacuna7.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna7.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna7.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna7MouseClicked(evt);
            }
        });
        jLacuna7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna7ActionPerformed(evt);
            }
        });

        jLacuna8.setText("jButton1");
        jLacuna8.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna8.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna8.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna8MouseClicked(evt);
            }
        });
        jLacuna8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna8ActionPerformed(evt);
            }
        });

        jLacuna9.setText("jButton1");
        jLacuna9.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna9.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna9.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna9MouseClicked(evt);
            }
        });
        jLacuna9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna9ActionPerformed(evt);
            }
        });

        jLabel2.setText("Jogadas: 0");

        jLabel3.setText("Vencedor: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLacuna7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLacuna8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLacuna9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLacuna1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLacuna4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLacuna5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLacuna2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLacuna6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLacuna3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLacuna1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLacuna2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLacuna3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLacuna4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLacuna5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLacuna6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLacuna9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLacuna8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLacuna7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jLacuna1.getAccessibleContext().setAccessibleName("jLacuna1");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void DadosDaTela(int Escolha_, int Dificuldade_, int QuemComeca_){
        Escolha=Escolha_;
        Dificuldade = Dificuldade_;
        QuemComeca= QuemComeca_;
        if(QuemComeca == 0)
            jogo.Escolher1();
        else{
            jogo.Escolher2();
            jogo.Jogar(jogo.QuemJoga(),Dificuldade);
            jogo.QuemVenceu();
            this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
            this.jLabel3.setText("Vencedor: "+jogo.getVencedor());     
        }
        this.setPosition();
    }
    private void jLacuna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna1ActionPerformed

    private void jLacuna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna2ActionPerformed

    private void jLacuna3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna3ActionPerformed

    private void jLacuna4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna4ActionPerformed

    private void jLacuna5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna5ActionPerformed

    private void jLacuna6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna6ActionPerformed

    private void jLacuna7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna7ActionPerformed

    private void jLacuna8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna8ActionPerformed

    private void jLacuna9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna9ActionPerformed

    private void jLacuna1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna1MouseClicked
        jogo.setJogada(0);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Jogador "+jogo.getVencedor()+" ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            }
            if(i==0){
                jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
        
    }//GEN-LAST:event_jLacuna1MouseClicked

    private void jLacuna1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna1MouseReleased

                  
    }//GEN-LAST:event_jLacuna1MouseReleased

    private void jLacuna2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna2MouseReleased
        
    }//GEN-LAST:event_jLacuna2MouseReleased

    private void jLacuna2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna2MouseClicked
        jogo.setJogada(1);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Jogador "+jogo.getVencedor()+" ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            }
            if(i==0){
                jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna2MouseClicked

    private void jLacuna3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna3MouseClicked
        jogo.setJogada(2);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Jogador "+jogo.getVencedor()+" ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            }
            if(i==0){
                jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna3MouseClicked

    private void jLacuna4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna4MouseClicked
        jogo.setJogada(3);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Jogador "+jogo.getVencedor()+" ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
      jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna4MouseClicked

    private void jLacuna5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna5MouseClicked
        jogo.setJogada(4);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Jogador "+jogo.getVencedor()+" ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
            jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna5MouseClicked

    private void jLacuna6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna6MouseClicked
        jogo.setJogada(5);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Jogador "+jogo.getVencedor()+" ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
            jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna6MouseClicked

    private void jLacuna7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna7MouseClicked
        jogo.setJogada(6);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Jogador "+jogo.getVencedor()+" ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
            jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna7MouseClicked

    private void jLacuna8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna8MouseClicked
        jogo.setJogada(7);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Jogador "+jogo.getVencedor()+" ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
                jogo.Reiniciar_Partida();
            if(QuemComeca == 0){
                jogo.Escolher1();
                }
            else{
                jogo.Escolher2();  
                jogo.Jogar(jogo.QuemJoga(), Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna8MouseClicked

    private void jLacuna9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna9MouseClicked
        jogo.setJogada(8);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Jogador "+jogo.getVencedor()+" ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
            jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna9MouseClicked
                                      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLacuna1;
    private javax.swing.JButton jLacuna2;
    private javax.swing.JButton jLacuna3;
    private javax.swing.JButton jLacuna4;
    private javax.swing.JButton jLacuna5;
    private javax.swing.JButton jLacuna6;
    private javax.swing.JButton jLacuna7;
    private javax.swing.JButton jLacuna8;
    private javax.swing.JButton jLacuna9;
    // End of variables declaration//GEN-END:variables
}
