/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ferreira
 */
public class InterfaceJogo extends javax.swing.JFrame {
    int Escolha,Dificuldade,QuemComeca;
    Jogo jogo;
    /**
     * Creates new form InterfaceJogo
     */
    public InterfaceJogo() {
        initComponents();
        setLocationRelativeTo(null);
        jogo=new Jogo();
        
            
    }
    private void setPosition(){
       if(jogo.Tabuleiro[0]==0){
        jLacuna1.setIcon(new ImageIcon(getClass().getResource("place.png")));
       }
       else if(jogo.Tabuleiro[0]==1){
          jLacuna1.setIcon(new ImageIcon(getClass().getResource("Human.png")));
       }
       else{
           jLacuna1.setIcon(new ImageIcon(getClass().getResource("Machine.png")));
       }
       if(jogo.Tabuleiro[1]==0){
         jLacuna2.setIcon(new ImageIcon(getClass().getResource("place.png")));
       }
       else if(jogo.Tabuleiro[1]==1){
          jLacuna2.setIcon(new ImageIcon(getClass().getResource("Human.png")));
          //jLacuna2.setText("1");
          
       }
       else {
           jLacuna2.setIcon(new ImageIcon(getClass().getResource("Machine.png")));
       }
       if(jogo.Tabuleiro[2]==0){
         jLacuna3.setIcon(new ImageIcon(getClass().getResource("place.png")));;
       }
       else if(jogo.Tabuleiro[2]==1){
          jLacuna3.setIcon(new ImageIcon(getClass().getResource("Human.png")));
       }
       else {
           jLacuna3.setIcon(new ImageIcon(getClass().getResource("Machine.png")));;
       }
       
       if(jogo.Tabuleiro[3]==0){
         jLacuna4.setIcon(new ImageIcon(getClass().getResource("place.png")));
       }
       else if(jogo.Tabuleiro[3]==1){
          jLacuna4.setIcon(new ImageIcon(getClass().getResource("Human.png")));
       }
       else {
           jLacuna4.setIcon(new ImageIcon(getClass().getResource("Machine.png")));
       }
       if(jogo.Tabuleiro[4]==0){
         jLacuna5.setIcon(new ImageIcon(getClass().getResource("place.png")));
       }
       else if(jogo.Tabuleiro[4]==1){
          jLacuna5.setIcon(new ImageIcon(getClass().getResource("Human.png")));
       }
       else {
           jLacuna5.setIcon(new ImageIcon(getClass().getResource("Machine.png")));
       }
       if(jogo.Tabuleiro[5]==0){
         jLacuna6.setIcon(new ImageIcon(getClass().getResource("place.png")));
       }
       else if(jogo.Tabuleiro[5]==1){
          jLacuna6.setIcon(new ImageIcon(getClass().getResource("Human.png")));
       }
       else {
           jLacuna6.setIcon(new ImageIcon(getClass().getResource("Machine.png")));
       }
       if(jogo.Tabuleiro[6]==0){
         jLacuna7.setIcon(new ImageIcon(getClass().getResource("place.png")));
       }
       else if(jogo.Tabuleiro[6]==1){
          jLacuna7.setIcon(new ImageIcon(getClass().getResource("Human.png")));
       }
       else {
           jLacuna7.setIcon(new ImageIcon(getClass().getResource("Machine.png")));
       }
       if(jogo.Tabuleiro[7]==0){
         jLacuna8.setIcon(new ImageIcon(getClass().getResource("place.png")));
       }
       else if(jogo.Tabuleiro[7]==1){
          jLacuna8.setIcon(new ImageIcon(getClass().getResource("Human.png")));
       }
       else {
           jLacuna8.setIcon(new ImageIcon(getClass().getResource("Machine.png")));
       }
       if(jogo.Tabuleiro[8]==0){
         jLacuna9.setIcon(new ImageIcon(getClass().getResource("place.png")));
       }
       else if(jogo.Tabuleiro[8]==1){
          jLacuna9.setIcon(new ImageIcon(getClass().getResource("Human.png")));
       }
       else {
           jLacuna9.setIcon(new ImageIcon(getClass().getResource("Machine.png")));
       }
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLacuna1 = new javax.swing.JButton();
        jLacuna2 = new javax.swing.JButton();
        jLacuna3 = new javax.swing.JButton();
        jLacuna4 = new javax.swing.JButton();
        jLacuna5 = new javax.swing.JButton();
        jLacuna6 = new javax.swing.JButton();
        jLacuna7 = new javax.swing.JButton();
        jLacuna8 = new javax.swing.JButton();
        jLacuna9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(409, 503));
        setMinimumSize(new java.awt.Dimension(409, 503));
        setPreferredSize(new java.awt.Dimension(409, 503));
        setResizable(false);
        getContentPane().setLayout(null);

        jLacuna1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/place.png"))); // NOI18N
        jLacuna1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna1.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna1.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLacuna1MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna1MouseClicked(evt);
            }
        });
        jLacuna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna1ActionPerformed(evt);
            }
        });
        getContentPane().add(jLacuna1);
        jLacuna1.setBounds(70, 160, 80, 80);
        jLacuna1.getAccessibleContext().setAccessibleName("jLacuna1");

        jLacuna2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/place.png"))); // NOI18N
        jLacuna2.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna2.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna2.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLacuna2MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna2MouseClicked(evt);
            }
        });
        jLacuna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna2ActionPerformed(evt);
            }
        });
        getContentPane().add(jLacuna2);
        jLacuna2.setBounds(150, 160, 80, 80);

        jLacuna3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/place.png"))); // NOI18N
        jLacuna3.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna3.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna3.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna3MouseClicked(evt);
            }
        });
        jLacuna3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna3ActionPerformed(evt);
            }
        });
        getContentPane().add(jLacuna3);
        jLacuna3.setBounds(230, 160, 80, 80);

        jLacuna4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/place.png"))); // NOI18N
        jLacuna4.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna4.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna4.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna4MouseClicked(evt);
            }
        });
        jLacuna4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna4ActionPerformed(evt);
            }
        });
        getContentPane().add(jLacuna4);
        jLacuna4.setBounds(70, 240, 80, 80);

        jLacuna5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/place.png"))); // NOI18N
        jLacuna5.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna5.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna5.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna5MouseClicked(evt);
            }
        });
        jLacuna5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna5ActionPerformed(evt);
            }
        });
        getContentPane().add(jLacuna5);
        jLacuna5.setBounds(150, 240, 80, 80);

        jLacuna6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/place.png"))); // NOI18N
        jLacuna6.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna6.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna6.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna6MouseClicked(evt);
            }
        });
        jLacuna6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna6ActionPerformed(evt);
            }
        });
        getContentPane().add(jLacuna6);
        jLacuna6.setBounds(230, 240, 80, 80);

        jLacuna7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/place.png"))); // NOI18N
        jLacuna7.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna7.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna7.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna7MouseClicked(evt);
            }
        });
        jLacuna7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna7ActionPerformed(evt);
            }
        });
        getContentPane().add(jLacuna7);
        jLacuna7.setBounds(70, 320, 80, 80);

        jLacuna8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/place.png"))); // NOI18N
        jLacuna8.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna8.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna8.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna8MouseClicked(evt);
            }
        });
        jLacuna8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna8ActionPerformed(evt);
            }
        });
        getContentPane().add(jLacuna8);
        jLacuna8.setBounds(150, 320, 80, 80);

        jLacuna9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/place.png"))); // NOI18N
        jLacuna9.setMaximumSize(new java.awt.Dimension(100, 100));
        jLacuna9.setMinimumSize(new java.awt.Dimension(100, 100));
        jLacuna9.setPreferredSize(new java.awt.Dimension(100, 100));
        jLacuna9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLacuna9MouseClicked(evt);
            }
        });
        jLacuna9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLacuna9ActionPerformed(evt);
            }
        });
        getContentPane().add(jLacuna9);
        jLacuna9.setBounds(230, 320, 80, 80);

        jLabel2.setText("Jogadas: 0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 12, 175, 64);

        jLabel3.setText("Vencedor: 0");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(205, 36, 175, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-90, -40, 530, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void DadosDaTela(int Escolha_, int Dificuldade_, int QuemComeca_){
        Escolha=Escolha_;
        Dificuldade = Dificuldade_;
        QuemComeca= QuemComeca_;
        if(QuemComeca == 0)
            jogo.Escolher1();
        else{
            jogo.Escolher2();
            jogo.Jogar(jogo.QuemJoga(),Dificuldade);
            jogo.QuemVenceu();
            this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
            this.jLabel3.setText("Vencedor: "+jogo.getVencedor());     
        }
        this.setPosition();
    }
    private void jLacuna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna1ActionPerformed

    private void jLacuna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna2ActionPerformed

    private void jLacuna3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna3ActionPerformed

    private void jLacuna4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna4ActionPerformed

    private void jLacuna5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna5ActionPerformed

    private void jLacuna6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna6ActionPerformed

    private void jLacuna7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna7ActionPerformed

    private void jLacuna8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna8ActionPerformed

    private void jLacuna9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLacuna9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLacuna9ActionPerformed

    private void jLacuna1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna1MouseClicked
        jogo.setJogada(0);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
                if(jogo.getVencedor()==1)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Humano! Parabéns ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==2)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Máquina! %&%&%*! -A Máquina ri de você  ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==3)
                    i= JOptionPane.showOptionDialog(rootPane, "Empatou!", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            }
            if(i==0){
                jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
        
    }//GEN-LAST:event_jLacuna1MouseClicked

    private void jLacuna1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna1MouseReleased

                  
    }//GEN-LAST:event_jLacuna1MouseReleased

    private void jLacuna2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna2MouseReleased
        
    }//GEN-LAST:event_jLacuna2MouseReleased

    private void jLacuna2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna2MouseClicked
        jogo.setJogada(1);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            if(jogo.getVencedor()==1)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Humano! Parabéns ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==2)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Máquina! %&%&%*! -A Máquina ri de você  ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==3)
                    i= JOptionPane.showOptionDialog(rootPane, "Empatou!", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            }
            if(i==0){
                jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna2MouseClicked

    private void jLacuna3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna3MouseClicked
        jogo.setJogada(2);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            if(jogo.getVencedor()==1)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Humano! Parabéns ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==2)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Máquina! %&%&%*! -A Máquina ri de você  ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==3)
                    i= JOptionPane.showOptionDialog(rootPane, "Empatou!", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            }
            if(i==0){
                jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna3MouseClicked

    private void jLacuna4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna4MouseClicked
        jogo.setJogada(3);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            if(jogo.getVencedor()==1)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Humano! Parabéns ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==2)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Máquina! %&%&%*! -A Máquina ri de você  ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==3)
                    i= JOptionPane.showOptionDialog(rootPane, "Empatou!", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
      jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna4MouseClicked

    private void jLacuna5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna5MouseClicked
        jogo.setJogada(4);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            if(jogo.getVencedor()==1)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Humano! Parabéns ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==2)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Máquina! %&%&%*! -A Máquina ri de você  ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==3)
                    i= JOptionPane.showOptionDialog(rootPane, "Empatou!", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
            jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna5MouseClicked

    private void jLacuna6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna6MouseClicked
        jogo.setJogada(5);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            if(jogo.getVencedor()==1)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Humano! Parabéns ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==2)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Máquina! %&%&%*! -A Máquina ri de você  ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==3)
                    i= JOptionPane.showOptionDialog(rootPane, "Empatou!", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
            jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna6MouseClicked

    private void jLacuna7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna7MouseClicked
        jogo.setJogada(6);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            if(jogo.getVencedor()==1)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Humano! Parabéns ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==2)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Máquina! %&%&%*! -A Máquina ri de você  ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==3)
                    i= JOptionPane.showOptionDialog(rootPane, "Empatou!", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
            jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna7MouseClicked

    private void jLacuna8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna8MouseClicked
        jogo.setJogada(7);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            if(jogo.getVencedor()==1)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Humano! Parabéns ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==2)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Máquina! %&%&%*! -A Máquina ri de você  ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==3)
                    i= JOptionPane.showOptionDialog(rootPane, "Empatou!", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
                jogo.Reiniciar_Partida();
            if(QuemComeca == 0){
                jogo.Escolher1();
                }
            else{
                jogo.Escolher2();  
                jogo.Jogar(jogo.QuemJoga(), Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna8MouseClicked

    private void jLacuna9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLacuna9MouseClicked
        jogo.setJogada(8);
        jogo.Jogar(jogo.QuemJoga(),Dificuldade);
        this.setPosition();
        jogo.QuemVenceu();
        this.jLabel2.setText("Jogadas: "+jogo.getNumero_de_jogadas());
        this.jLabel3.setText("Vencedor: "+jogo.getVencedor());
        if(jogo.getVencedor()!=0){
            String[] opcoes = new String[3];
            opcoes[0]= new String("Reiniciar Esta Partida");
            opcoes[1]= new String("Iniciar uma nova partida");
            opcoes[2]= new String("Fechar jogo");
            int i=-1;
            while(i==-1){
            if(jogo.getVencedor()==1)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Humano! Parabéns ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==2)
                    i= JOptionPane.showOptionDialog(rootPane, "Vencedor: Máquina! %&%&%*! -A Máquina ri de você  ", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
                if(jogo.getVencedor()==3)
                    i= JOptionPane.showOptionDialog(rootPane, "Empatou!", "Vencedor",0, JOptionPane.INFORMATION_MESSAGE, null,opcoes,null);
            
            }
            if(i==0){
            jogo.Reiniciar_Partida();
            if(QuemComeca == 0)
            jogo.Escolher1();
                else{
                jogo.Escolher2();
                jogo.Jogar(jogo.QuemJoga(),Dificuldade);
                }
            this.setPosition();
            this.jLabel2.setText("Jogadas: "+0);
            this.jLabel3.setText("Vencedor: "+0);
            }
            else if(i==2){
                this.dispose();
            }
            else if(i==1){
                this.dispose();
                EscolherModo tela = new EscolherModo();
                tela.setVisible(true);
                 
            }
            
        }
    }//GEN-LAST:event_jLacuna9MouseClicked
                                      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLacuna1;
    private javax.swing.JButton jLacuna2;
    private javax.swing.JButton jLacuna3;
    private javax.swing.JButton jLacuna4;
    private javax.swing.JButton jLacuna5;
    private javax.swing.JButton jLacuna6;
    private javax.swing.JButton jLacuna7;
    private javax.swing.JButton jLacuna8;
    private javax.swing.JButton jLacuna9;
    // End of variables declaration//GEN-END:variables
}
